<a href="https://colab.research.google.com/github/s-ribansky/RedditProject_NLPDL/blob/master/Project_containing_Twitter_data_as_Well.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
! git clone https://github.com/NVIDIA/apex
os.chdir('apex')
!pip install -v --no-cache-dir ./

Cloning into 'apex'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6593 (delta 0), reused 0 (delta 0), pack-reused 6589
Receiving objects: 100% (6593/6593), 13.70 MiB | 28.41 MiB/s, done.
Resolving deltas: 100% (4383/4383), done.
Created temporary directory: /tmp/pip-ephem-wheel-cache-2ubyx3s6
Created temporary directory: /tmp/pip-req-tracker-_hzz3_r1
Created requirements tracker '/tmp/pip-req-tracker-_hzz3_r1'
Created temporary directory: /tmp/pip-install-7cq6y5vk
Processing /content/apex
  Created temporary directory: /tmp/pip-req-build-oniiy1mi
  Added file:///content/apex to build tracker '/tmp/pip-req-tracker-_hzz3_r1'
    Running setup.py (path:/tmp/pip-req-build-oniiy1mi/setup.py) egg_info for package from file:///content/apex
    Running command python setup.py egg_info
    torch.__version__  =  1.4.0
    running egg_info
    creating /tmp/pip-req-build-oniiy1mi/pip-egg-info/apex.

In [0]:
#a=[]
#while(1):
  #a.append('1')

In [0]:
#Do in console : To prevent this, we can run the following in the page console. To access this, right click on the page and choose Inspect (Command + Shift + C for Mac users). Then click on Console and paste the following code snippet:


#function ClickConnect(){
#console.log("Working");
#document.querySelector("colab-toolbar-button").click()
#}setInterval(ClickConnect,50000)

In [4]:
!pip install simpletransformers
!pip install transformers


     |████████████████████████████████| 163kB 3.4MB/s 
     |████████████████████████████████| 573kB 71.8MB/s 
     |████████████████████████████████| 3.8MB 61.6MB/s 
     |████████████████████████████████| 204kB 78.4MB/s 
     |████████████████████████████████| 890kB 52.3MB/s 
     |████████████████████████████████| 1.0MB 45.0MB/s 
  Created wheel for seqeval: filename=seqeval-0.0.12-cp36-none-any.whl size=7424 sha256=8d13583bc8c4019a4f7b8556d92fc0f8a4e4b09414c8dd829e987cd268a7a22f
  Stored in directory: /root/.cache/pip/wheels/4f/32/0a/df3b340a82583566975377d65e724895b3fad101a3fb729f68
  Created wheel for sacremoses: filename=sacremoses-0.0.41-cp36-none-any.whl size=893334 sha256=592592b8634ef6fba7535c837fff20bcb3581ccfb93361e7dfb9559ee3452c5f
  Stored in directory: /root/.cache/pip/wheels/22/5a/d4/b020a81249de7dc63758a34222feaa668dbe8ebfe9170cc9b1
Successfully built seqeval sacremoses
ERROR: transformers 2.8.0 has requirement tokenizers==0.5.2, but you'll have tokenizers 0.7.0 which

In [0]:
from argparse import Namespace
from collections import Counter
import json
import os
import string
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm_notebook
from apex import amp
from simpletransformers.classification import ClassificationModel
#from simpletransformers.experimental.classification import ClassificationModel

import pandas as pd
import logging
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import random


In [0]:
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)


In [7]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/database2.csv')

In [0]:
twitterdataraw=pd.read_pickle('/content/drive/My Drive/Colab Notebooks/labeled_data.p')

In [49]:
print(twitterdataraw.iloc[0,5])

!!! RT @mayasolovely: As a woman you shouldn't complain about cleaning up your house. &amp; as a man you should always take the trash out...


In [45]:
dataedit=pd.DataFrame(twitterdataraw.iloc[:,5])
dataedit.columns=['text']
dataedit.insert(1,"labels",np.ones(len(twitterdataraw),dtype=int))
indx=np.where(twitterdataraw.iloc[:,4]==2)
print(indx[0])
dataedit.iloc[indx[0],1]=0


[    0    40    63 ... 24767 24779 24782]


In [46]:
print(dataedit)
print(np.zeros(len(twitterdataraw)))

                                                    text  labels
0      !!! RT @mayasolovely: As a woman you shouldn't...       0
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...       1
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...       1
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...       1
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...       1
...                                                  ...     ...
25291  you's a muthaf***in lie &#8220;@LifeAsKing: @2...       1
25292  you've gone and broke the wrong heart baby, an...       0
25294  young buck wanna eat!!.. dat nigguh like I ain...       1
25295              youu got wild bitches tellin you lies       1
25296  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...       0

[24783 rows x 2 columns]
[0. 0. 0. ... 0. 0. 0.]


In [50]:
dataedit['text'] = dataedit['text'].astype(str)
print (dataedit['text'].dtype)
print (dataedit['labels'].dtype)

object
int64


In [141]:
print(dataedit.shape)
print(sum(dataedit.iloc[:,1]))
print(sum(dataedit.iloc[:,1])/dataedit.shape[0])
print(sum(df.iloc[:,1])/df.shape[0])
ids=np.where(twitterdataraw.iloc[:,4]==2)[0]
print(ids.shape)
i=0
while(i<2780):
  randomtmp=np.array(random.randrange(len(dataedit)))
  if np.any(np.in1d(ids,randomtmp))==0:
    ids=np.append(ids,randomtmp)
    i+=1
    #print("worked")
  #else:
    #print("duplicate")
print(ids.shape)

dataedit_balanced=dataedit.iloc[ids,:]
print(dataedit_balanced)
print(sum(dataedit_balanced.iloc[:,1])/dataedit_balanced.shape[0])

#ids=random.sample(range(0, dataedit.shape[0]), 60)
#reduced_dataset=dataedit.iloc[ids,:]
#print(reduced_dataset.shape)
#print(reduced_dataset)
#print(sum(reduced_dataset.iloc[:,1]))

(24783, 2)
20620
0.8320219505306057
0.39506067338916423
(4163,)
(6943,)
                                                    text  labels
0      !!! RT @mayasolovely: As a woman you shouldn't...       0
40       " momma said no pussy cats inside my doghouse "       0
63     "@Addicted2Guys: -SimplyAddictedToGuys http://...       0
66     "@AllAboutManFeet: http://t.co/3gzUpfuMev" woo...       0
67     "@Allyhaaaaa: Lemmie eat a Oreo &amp; do these...       0
...                                                  ...     ...
6096   @emmyhighr0ller @Cyberobama \nyou sound like a...       1
22740   Trust no nigga, fear no bitch &#128074;&#128142;       1
19117  RT @bugattibeez: pussy still taste like McDona...       1
4447                              @OMG_itsBrooke hey hoe       1
1819   &#8220;@iDntWearCondoms: U get what u put in. ...       1

[6943 rows x 2 columns]
0.4004032838830477


In [132]:
    randomtmp=np.array(25000)
    print(randomtmp)
    print(ids)
    ids=np.append(ids,randomtmp)
    print(ids)
    print(ids.shape)

25000
[    0    40    63 ... 25000 25000 25000]
[    0    40    63 ... 25000 25000 25000]
(4167,)


In [51]:
df['text'] = df['text'].astype(str)
print (df['text'].dtype)
print (df['labels'].dtype)


object
int64


In [0]:
print(df.shape)
ids=random.sample(range(0, df.shape[0]), 60)
reduced_dataset=df.iloc[ids,:]
print(reduced_dataset.shape)
print(reduced_dataset)
print(sum(reduced_dataset.iloc[:,1]))

In [143]:
#df_train, df_eval = train_test_split(reduced_dataset, test_size=0.2)
#df_train, df_eval = train_test_split(df, test_size=0.2)
df_train, df_eval = train_test_split(dataedit_balanced, test_size=0.2)

print (df['text'].dtype)

object


In [144]:
train_df = df_train
eval_df = df_eval
print(train_df.shape)
print(eval_df.shape[0])


(5554, 2)
1389


In [0]:
#model = ClassificationModel('distilbert', 'distilbert-base-uncased', use_cuda=True) 
model = ClassificationModel('distilbert', '/content/drive/My Drive/greatmodel/', use_cuda=True)

In [0]:
arguments={
      "sliding_window": True,
      "reprocess_input_data": True,
      "overwrite_output_dir": True,
      "stride": 0.8,
      "max_seq_length": 128,
      "best_model_dir": "/content/drive/My Drive/bestmodel/",
      "cache_dir": "/content/drive/My Drive/cache/",
      "output_dir": "/content/drive/My Drive/output/",
      "save_steps": train_df.shape[0],

      "logging_steps": eval_df.shape[0],
      "train_batch_size": 8,
      "eval_batch_size": 8,
      "gradient_accumulation_steps": 1,
      "num_train_epochs": 1,
      "weight_decay": 0,
      "learning_rate": 4e-5,
      "evaluate_during_training":True,
      "evaluate_during_training_steps": eval_df.shape[0],
      "evaluate_during_training_verbose": True,
      "use_early_stopping": True,
      "early_stopping_patience": 35,
      "early_stopping_delta": 0,
      "early_stopping_metric": "eval_loss",
      "early_stopping_metric_minimize": True,
      "loss_scale":'dynamic'}
#gradient_accumulation_steps could save disk space for slower training

In [148]:
model.train_model(train_df,eval_df=eval_df, args=arguments)

INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
INFO:simpletransformers.classification.classification_model: Sliding window enabled


INFO:simpletransformers.classification.classification_model: 5566 features created from 5554 samples.



Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic


INFO:simpletransformers.classification.classification_model:   Starting fine-tuning.


Running loss: 1.276413Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Running loss: 1.646286

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:113: UserWarning: Seems like `optimizer.step()` has been overridden after learning rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)


Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
Running loss: 1.206928Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 8192.0
Running loss: 0.303012Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 4096.0
Running loss: 0.007239


INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
INFO:simpletransformers.classification.classification_model: Sliding window enabled
INFO:simpletransformers.classification.classification_model: 1389 features created from 1389 samples.
INFO:simpletransformers.classification.classification_model:{'mcc': 0.9143909344094645, 'tp': 499, 'tn': 834, 'fp': 27, 'fn': 29, 'eval_loss': 0.16147486226899282}


INFO:simpletransformers.classification.classification_model: Training of distilbert model complete. Saved to /content/drive/My Drive/output/.


In [68]:
import sklearn

# Evaluate on evaluation set
result, model_outputs, wrong_predictions = model.eval_model(eval_df, acc=sklearn.metrics.accuracy_score)

INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.


INFO:simpletransformers.classification.classification_model:{'mcc': 0.7667586998091058, 'tp': 6114, 'tn': 10533, 'fp': 771, 'fn': 1305, 'acc': 0.8891203332799231, 'eval_loss': 0.3644821956560385}


In [66]:
print(model.results)


{'mcc': 0.7694478103552779, 'tp': 1496, 'tn': 2675, 'fp': 179, 'fn': 331, 'acc': 0.89104892117069, 'eval_loss': 0.37122585016077086}


In [150]:
# Evaluate on twitter set
result, model_outputs, wrong_predictions = model.eval_model(eval_df, acc=sklearn.metrics.accuracy_score)

INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
INFO:simpletransformers.classification.classification_model: Sliding window enabled


INFO:simpletransformers.classification.classification_model: 1389 features created from 1389 samples.


INFO:simpletransformers.classification.classification_model:{'mcc': 0.9143909344094645, 'tp': 499, 'tn': 834, 'fp': 27, 'fn': 29, 'eval_loss': 0.16147486226899282, 'acc': 0.9596832253419726}


In [62]:
x_predict = input("Hello, how are you doing?")

Hello, how are you doing?you idiot


In [63]:
predictions, raw_outputs = model.predict([x_predict])
print(predictions)

INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.



[1]
